
@token = {{$processEnv GH_TOKEN}}
POST https://api.github.com/repos/technologiestiftung/repository-dispatch-poc/dispatches
Authorization: Bearer {{token}}
X-GitHub-Api-Version: 2022-11-28
Content-Type: application/json
Accept: application/vnd.github+json

{"event_type":"foo", "client_payload":{"environment":"test"}}